---
pve_group: glacier
pve_watchdog: ipmi
# pve_ssl_private_key: "{{ lookup('file', pve_group + '/' + inventory_hostname + '.key') }}"
# pve_ssl_certificate: "{{ lookup('file', pve_group + '/' + inventory_hostname + '.pem') }}"
pve_cluster_enabled: no
pve_groups:
  - name: administrators
    comment: Administrators
  - name: automation
    comment: Automation Users
  - name: developers
    comment: Developer Users
pve_acls:
  - path: /
    roles: [ "Administrator" ]
    groups: [ "administrators" ]
  - path: /
    roles: [ "Monitoring" ]
    groups: [ "developers" ]
  - path: /
    roles: [ "Terraform" ]
    groups: [ "automation" ]
  - path: /
    roles: [ "Packer" ]
    groups: [ "automation" ]
pve_roles:
  - name: Monitoring
    privileges:
      - "Sys.Modify"
      - "Sys.Audit"
      - "Datastore.Audit"
      - "VM.Monitor"
      - "VM.Audit"
  - name: Terraform
    privileges:
      - Datastore.AllocateSpace
      - Datastore.Audit
      - Pool.Allocate
      - Sys.Audit
      - Sys.Console
      - VM.Allocate
      - VM.Audit
      - VM.Clone
      - VM.Config.CDROM
      - VM.Config.Cloudinit
      - VM.Config.CPU
      - VM.Config.Disk
      - VM.Config.HWType
      - VM.Config.Memory
      - VM.Config.Network
      - VM.Config.Options
      - VM.Migrate
      - VM.Monitor
      - VM.PowerMgmt
  - name: Packer
    privileges:
      - VM.Config.Disk
      - VM.Config.CPU
      - VM.Config.Cloudinit
      - VM.Clone
      - VM.Config.Memory
      - Datastore.AllocateSpace
      - Sys.Modify
      - VM.Config.Options
      - VM.Console
      - VM.Allocate
      - VM.Audit
      - VM.Config.CDROM
      - VM.Config.Network
      - VM.PowerMgmt
      - VM.Config.HWType
      - VM.Monitor
# pve_storages:
#   - name: localdir
#     type: dir
#     content: [ "images", "iso", "backup" ]
#     path: /plop
#     maxfiles: 4
# pve_ssh_port: 22

# interfaces_template: "interfaces-{{ pve_group }}.j2"
