---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: detect-private-key
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.28.0
    hooks:
      - id: yamllint
        args: [-c=.yamllint]
  # - repo: https://github.com/ansible-community/ansible-lint.git
  #   rev: v6.17.2
  #   hooks:
  #     - id: ansible-lint
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.4
    hooks:
      - id: shellcheck
        args: ["--severity=warning"]
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.1
    hooks:
      - id: remove-crlf
      - id: remove-tabs
  - repo: https://github.com/sirosen/texthooks
    rev: 0.4.0
    hooks:
      - id: fix-smartquotes
  # - repo: https://github.com/gruntwork-io/pre-commit
  #   rev: v0.1.22
  #   hooks:
  #     - id: tflint
  #       args:
  #         - "--module"
  #         - "--deep"
  #         - "--config=.tflint.hcl"
  #     - id: terraform-validate
  #     - id: terraform-fmt
  # - repo: git://github.com/antonbabenko/pre-commit-terraform
  #   rev: v1.81.2
  #   hooks:
  #     - id: terraform_tfsec
  #     - id: terraform_docs
  #     - id: checkov

# brew tap liamg/tfsec
# brew install terraform-docs tflint tfsec checkov
# brew install pre-commit gawk coreutils
