---
# Install and setup zerotier
# - name: Include zerotier setup
#   include: zerotier.yaml

# Setup/Initilize proxmox
- name: Include proxmox prepare initialisation
  import_playbook: proxmox.pre.yml
- name: Include proxmox initialisation
  import_playbook: proxmox.yml

# Install basic packages
- name: Include basic packages
  import_playbook: packages.yaml

# Install timeshift and make a snapshot
- name: Include timeshift setup
  import_playbook: timeshift.yaml

# Install and setup wakeonlan capabilities
# - name: Include wakeonlan setup
#   include: wakeonlan.yaml

# Install github-runner
- name: Include github-runner setup
  import_playbook: github-runner.yaml
