---
- name: Preprare the development machine with basic settings, packages and networking
  hosts: glacier

  roles:
    - role: jakoberpf.proxmox
      vars:
        pve_reboot_on_kernel_update: false
